version: "3.3"
services:
  ros-ubuntu:
    container_name: multi_robot_task
    build:
      context: ../
      dockerfile: docker/wsl.dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
      - CYCLONEDDS_URI=${CYCLONEDDS_URI}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    runtime: nvidia
    privileged: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ../colcon_ws:/home/colcon_ws
