services:
  ros-wsl:
    profiles: ["wsl"]
    build:
      context: ../
      dockerfile: docker/wsl.dockerfile
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - ../colcon_ws:/home/colcon_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia

  ros-ubuntu:
    profiles: ["ubuntu"]
    build:
      context: ../
      dockerfile: docker/ubuntu.dockerfile
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - ../colcon_ws:/home/colcon_ws
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
